on:
  release:
    types:
      - created
  # push:
  #   branches:    
  #     - 2021-08-18/build-with-gh-actions
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Setup
        run: sudo snap install snapcraft --classic && sudo snap install lxd
      - name: Init LXD
        uses: bonddim/action-lxd-init@v1
      - name: Compile
        run: snapcraft --use-lxd
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: succedo
      #     path: succedo_*.snap
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: succedo_*.snap
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
