on:
  # release:
  #   types:
  #     - created
  push:
    branches:    
      - 2021-08-18/build-with-gh-actions
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Setup
        run: sudo snap install snapcraft --classic && sudo snap install lxd
      - name: Configure
        run: sudo lxd init --preseed < lxd.yaml
      - name: Compile
        run: snapcraft --use-lxd
      - uses: actions/upload-artifact@v2
          with:
            name: succedo
            path: succedo_*.snap
